defaults:
  - _self_
  - beta
  - data: base

predictor:
  _target_: beta.model.BetaPredictor
  lr: 0.0001

  model:
    _target_: beta.model.nn.BetaModel
    input_size: ${len:${data.dataset.series}}
    lookback: ${data.dataset.lookback}
    hidden_size: 48
    num_layers: 8
    dropout: 0.02

run:
  dev: false
  progress: false
  min_epochs: 150
  max_epochs: 1500
