defaults:
  - _self_
  - beta

data:
  _target_: beta.data.BetaDataModule
  batch_size: 16
  predict: 100
  shuffle: true
  split: 0.80

  dataset:
    _target_: beta.data.BetaDataset
    lookback: 25
    subset: null

    series:
      - _target_: beta.data.BetaSeries
        stock: dataset/daily/pl/wse stocks/ale.txt
        index: dataset/daily/pl/wse indices/wig.txt
        column: <CLOSE>
        rates:
          _target_: beta.data.rates.Daily
          rate: LOG

        beta:
          _target_: beta.data.index.Rolling
          window: 150

      - _target_: beta.data.BetaSeries
        stock: dataset/daily/pl/wse stocks/ale.txt
        index: dataset/daily/pl/wse indices/wig.txt
        column: <CLOSE>
        rates:
          _target_: beta.data.rates.Daily
          rate: LOG

        beta:
          _target_: beta.data.index.Rolling
          window: 75

predictor:
  _target_: beta.model.BetaPredictor
  lr: 0.0001

  model:
    _target_: beta.model.nn.BetaModel
    input_size: ${len:${data.dataset.series}}
    lookback: ${data.dataset.lookback}
    hidden_size: 48
    num_layers: 8
    dropout: 0.02

run:
  dev: false
  min_epochs: 150
  max_epochs: 1500
