defaults:
  - _self_
  - beta

data:
  _target_: beta.data.BetaDataModule
  batch_size: 2
  shuffle: true
  split: 0.80

  dataset:
    _target_: beta.data.BetaDataset
    lookback: 25
    subset: null

    series:
      - _target_: beta.data.BetaSeries
        stock: ${experiment.dataset_dir}/${experiment.stock_dir}/${experiment.stock_name}.txt
        index: ${experiment.dataset_dir}/${experiment.index_dir}/${experiment.index_name}.txt
        column: <CLOSE>
        rates:
          _target_: beta.data.rates.Daily
          rate: log

        beta:
          _target_: beta.data.index.Rolling
          window: 150

predictor:
  _target_: beta.model.BetaPredictor
  lr: 0.0001

  model:
    _target_: beta.model.nn.BetaModel
    input_size: 1
    hidden_size: 48
    num_layers: 8
    dropout: 0.02
    lookback: ${data.dataset.lookback}

experiment:
  dataset_dir: dataset/daily/pl
  stock_dir: "wse stocks"
  stock_name: ale
  index_dir: "wse indices"
  index_name: wig

run:
  dev: false
  min_epochs: 150
  max_epochs: 1500
